name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master
  schedule:
    # Run every day at 2 AM UTC to test with latest WordPress
    - cron: '0 2 * * *'
  workflow_dispatch:

# Prevents multiple runs from conflicting with each other
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test with WordPress
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']
        wordpress: ['latest', '6.8', '6.7']
        include:
          - php: '8.2'
            wordpress: 'minimum'
            WP_VERSION: '6.0'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, gd, imagick
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: make install

      - name: Run plugin tests
        run: composer test

      - name: Build plugin
        run: make build

      - name: Run Plugin Check
        uses: WordPress/plugin-check-action@v1
        with:
          build-dir: 'build/aquamark/'

  update-tested-up-to:
    name: Update Tested Up To & Tag
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    needs: [test]
    # Add permissions for writing contents and creating tags
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all history for all tags to find the latest one
          fetch-depth: 0

      - name: Get latest WordPress version
        id: wp_version
        run: |
          LATEST_WP_VERSION=$(curl -s https://api.wordpress.org/core/version-check/1.7/ | jq -r '.offers[0].version')
          LATEST_WP_VERSION_MAJOR=$(echo "$LATEST_WP_VERSION" | cut -d '.' -f 1,2)
          echo "latest=$LATEST_WP_VERSION_MAJOR" >> $GITHUB_OUTPUT

      - name: Get current Tested Up To version from readme.txt
        id: current_version
        run: |
          CURRENT_README_VERSION=$(grep -i "Tested up to:" readme.txt | awk -F': ' '{print $2}' | tr -d '[:space:]')
          echo "current=$CURRENT_README_VERSION" >> $GITHUB_OUTPUT
          echo "Comparing latest WP version (${{ steps.wp_version.outputs.latest }}) with readme version ($CURRENT_README_VERSION)"

      - name: Update readme.txt if needed
        if: steps.wp_version.outputs.latest != steps.current_version.outputs.current
        run: |
          sed -i "s/Tested up to: .*/Tested up to: ${{ steps.wp_version.outputs.latest }}/" readme.txt
          echo "readme.txt updated to version ${{ steps.wp_version.outputs.latest }}"

      - name: Commit changes if readme was updated
        id: commit
        if: steps.wp_version.outputs.latest != steps.current_version.outputs.current
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update Tested up to version to ${{ steps.wp_version.outputs.latest }}"
          file_pattern: readme.txt

      - name: Bump patch version and push tag
        if: steps.commit.outputs.changes_detected == 'true'
        id: tag_version
        uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true # Prefixes the tag with 'v'
          DEFAULT_BUMP: patch # Increments the patch version (e.g., 1.2.3 -> 1.2.4)

      - name: Log new tag
        if: steps.commit.outputs.changes_detected == 'true'
        run: echo "Successfully created and pushed new tag ${{ steps.tag_version.outputs.new_tag }}"

      - name: Log no changes
        if: steps.wp_version.outputs.latest == steps.current_version.outputs.current
        run: echo "WordPress 'Tested up to' version is already up to date."

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build plugin
        run: make build

      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Get Release Notes From Changelog
        id: get_release_notes
        uses: nickohold/changelog-version-extractor@v1.0.0
        with:
          version_prefix: "## ["
          version: ${{ steps.get_version.outputs.version }}
          changelog_path: 'CHANGELOG.md'

      - name: Create GitHub Release and Upload Artifact
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.get_release_notes.outputs.changelog }}
          generateReleaseNotes: false
          artifacts: "aquamark.zip"

  deploy:
    name: WordPress Plugin Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [release]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build plugin
        run: make build

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG : aquamark
          BUILD_DIR: build/aquamark/
